# based on action from https://github.com/poldrack/psych-open-science-guide

name: Build jupyter book

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U jupyter-book
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build book
      run: jb build ./site
    - name: Move book into Jekyll-friendly format
      run: |
        mv ./site/_build/html ./book
        UNDER_DIRECTORIES=$(ls -d ./book/_* | xargs -n 1 basename)
        for U_D in $UNDER_DIRECTORIES
        do 
          mv ./book/${U_D} ./book/${U_D:1}
          grep -rl ${U_D} ./book | xargs sed -i 's/${U_D}/${U_D:1}/g' || true
        done
    - name: Commit
      run: |
        git rm -rf site .github || true
        git add * || true
        git commit -m "Publish \"$(git log -1 --pretty=%B)\"" || true
    - name: Push book changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SITE_PUSH_SECRET }}
        branch: gh-pages
