# based on action from https://github.com/poldrack/psych-open-science-guide

name: Build jupyter book

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U jupyter-book
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build book
      run: jb build ./site
    - name: Move book into Jekyll-friendly format
      run: |
        mv ./site/_build/html ./book
        mv ./book/panels_static ./book/panels_static
        mv ./book/_sources ./book/sources
        mv ./book/_static ./book/static
        grep -rl _panels_static ./book | xargs sed -i 's/panels_static/panels_static/g'
        grep -rl _sources ./book | xargs sed -i 's/_sources/sources/g'
        grep -rl _static ./book | xargs sed -i 's/_static/static/g'
    - name: Commit
      run: |
        git rm -rf site .git .github
        git add *
        git commit -m "Publish \"$(git log -1 --pretty=%B)\""
    - name: Push book changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SITE_PUSH_SECRET }}
        branch: gh-pages
