# based on action from https://github.com/poldrack/psych-open-science-guide

name: Build jupyter book

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U jupyter-book
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build book
      run: |
        jb build ./site
        # cp -r images ./guide/_build/html
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.SITE_PUSH_SECRET }}
        publish_dir: ./site/_build/html
